### ISSUE TITLE
Makdown issue on VSC marketplace

### ISSUE THREAD

**Issue by jetmartin** [jetmartin/bats#10]
The Markdown syntaxe is not managed the same way between GitHub and marketplace.visualstudio.com or the VSC Extension window.

See : https://marketplace.visualstudio.com/items?itemName=jetmartin.bats
or bellow
![image](https://user-images.githubusercontent.com/6155133/67900695-5c47f880-fb65-11e9-9d27-0708f86b3447.png)

**Comment by virgilwashere** [comment]
https://code.visualstudio.com/api/references/extension-manifest#marketplace-presentation-tips


I think using high bit ANSI code will work:

`🦇` vs `:bat:`
`✖`  vs  `:heavy_multiplication_x:`

Confirming.

**Comment by virgilwashere** [comment]
@jetmartin push PR #11 to fix README and CHANGELOG
