### ISSUE TITLE
vscodium 

### ISSUE THREAD

**Issue by ghost** [jetmartin/bats#12]
Hi, 
I was wondering if I could ask you to publish the extention for vscodim, at https://open-vsx.org

Thanks in advance.

**Comment by jetmartin** [comment]
Hi,

For sure you can ask ;)
Good question. No reasons not to do it.
I'm currently very busy so you may has to wait a bit...
It should not be very time consuming so i will look a that some day.

Best.

**Comment by ghost** [comment]
Thanks

**Comment by jetmartin** [comment]
Ok, I'm more than late on this one but it's done.
Best.
