### ISSUE TITLE
Add ✂️ snippets for `bats-assert`

### ISSUE THREAD

**Issue by virgilwashere** [jetmartin/bats#6]
I've got a PR for `bats-assert` ✂️ snippets ready to submit when you have accepted #5.

https://github.com/virgilwashere/bats-vscode/tree/bat-assert

**Comment by jetmartin** [comment]
Hi,
I'll take a look next week as well as your PR.
Best.
J-Et.

**Comment by jetmartin** [comment]
Hi Virgil,

Thank you for your PR.
Your work on Bats-assert looks great too.

My concern before adding bats-assert snippets was to knew if It's better to add a config option to enable it (if you don't have the module installed).
But with the very nice work you did on the README.md, I guess it's no longer a concern to have.

Feel free to push your PR, I will review and test it before publishing a new release of the plugin.

Best regards from France.

J-Et.
